version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      APP_ENV: development
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    stdin_open: true
    tty: true
volumes:
  bundle:
